export const SCHEDULE = [
  { month: 1, day: 4, name: "Phan Thị Thanh Thảo" },
  { month: 1, day: 5, name: "Nguyễn Thành Hưng" },
  { month: 1, day: 8, name: "Nguyễn Minh Hà" },
  { month: 2, day: 22, name: "Dương Thanh Nam" },
  { month: 3, day: 5, name: "Hoàng Văn Thao" },
  { month: 4, day: 12, name: "Nguyễn Thị Tú Phương" },
  { month: 6, day: 13, name: "Nguyễn Việt Dũng" },
  { month: 9, day: 2, name: "Nguyễn Việt Quốc An" },
  { month: 9, day: 4, name: "Nguyễn Chiến Thắng" },
  { month: 9, day: 4, name: "Nguyễn Thị Thanh Tâm" },
  { month: 9, day: 8, name: "Nguyễn Thị Hằng" },
  { month: 10, day: 16, name: "Phạm Hoàng Duy Vũ" },
  { month: 10, day: 20, name: "Nguyễn Tiến Đạt" },
  { month: 10, day: 30, name: "Nguyễn Sơn Hải" },
  { month: 11, day: 5, name: "Nguyễn Tuấn Hưng" },
  { month: 11, day: 14, name: "Trần Ngọc Sơn" },
  { month: 12, day: 26, name: "Cao Tuấn Anh" },
];
